# Generated by Django 2.1.3 on 2018-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20181207_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notas',
            name='exam_date',
            field=models.DateField(max_length=255),
        ),
    ]
