# Generated by Django 2.1.3 on 2018-12-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20181207_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='exam_date',
            field=models.DateField(verbose_name='Fecha de Examen'),
        ),
    ]
