# Generated by Django 2.1.3 on 2018-12-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_auto_20181207_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='alumnos',
        ),
    ]
